#!/bin/bash


declare -a packages=(
  "dnsutils"
  "git"
  "python3"
  "python3-venv"
  "mercurial"
  "tree"
  "vim"
  "openssh-client"
  "openssh-server"
  "openssh-sftp-server"
)

# Iterate the string array using for loop
for val in ${packages[@]}; do
   apt-get install $val
done